export const blogPosts = [
  {
    slug: 'managing-anxiety',
    coverImage: '/img/blog-anxiety.webp',
    category: 'Anxiety',
    readMinutes: 4,
    en: {
      title: 'Five Grounding Techniques for Everyday Anxiety',
      excerpt: 'Simple, practical tools you can use anywhere to calm an anxious moment — no special equipment required.',
      body: [
        "Anxiety has a way of showing up uninvited — in a meeting, at the grocery store, in the quiet minutes before sleep. If you've ever felt your heart race or your thoughts spiral for no clear reason, you're not alone, and you're not broken. Anxiety is your nervous system trying to protect you, even when there's nothing to protect you from. The good news is that you don't need a therapist's office to start working with it. Here are five grounding techniques you can use anywhere, the next time anxiety shows up.",
        "Start with your senses. Name five things you can see, four you can touch, three you can hear, two you can smell, and one you can taste. This simple exercise, sometimes called the 5-4-3-2-1 technique, pulls your attention out of anxious thoughts and back into your body and your surroundings. It works because anxiety often lives in the future — in what might happen — while your senses only exist in the present.",
        "Try box breathing. Breathe in slowly for a count of four, hold for four, breathe out for four, and hold again for four before repeating. It sounds almost too simple to matter, but slowing your breath signals safety to your nervous system, which can quiet a racing heart within a minute or two.",
        "Move your body, even briefly. A short walk, stretching your arms overhead, or simply unclenching your jaw and shoulders can interrupt the physical tension that anxiety creates. You don't need a full workout — even thirty seconds of intentional movement can shift how your body is holding stress.",
        "Name what you're feeling, out loud if you can. \"I'm feeling anxious right now\" sounds small, but research on affect labelling shows that putting a feeling into words can reduce its intensity. You're not trying to talk yourself out of the anxiety — you're simply acknowledging it, which often takes away some of its power.",
        "These techniques won't erase anxiety, and they're not meant to replace support when anxiety is affecting your daily life, your sleep, or your relationships. If anxiety has been following you around for a while, it might be worth talking to someone. In our work together, we build a toolkit that's suited specifically to you — not a generic list, but strategies that actually fit your life, your triggers, and your goals. If you'd like to talk, a free 15-minute consultation is a low-pressure way to start.",
      ],
    },
    fr: {
      title: "Cinq techniques d'ancrage pour l'anxiété du quotidien",
      excerpt: "Des outils simples et concrets que vous pouvez utiliser n'importe où pour apaiser un moment d'anxiété — sans matériel particulier.",
      body: [
        "L'anxiété a le don de s'inviter sans prévenir — dans une réunion, à l'épicerie, dans les minutes calmes avant de s'endormir. Si vous avez déjà senti votre cœur s'emballer ou vos pensées s'emballer sans raison claire, vous n'êtes pas seul(e), et vous n'êtes pas brisé(e). L'anxiété est votre système nerveux qui tente de vous protéger, même lorsqu'il n'y a rien dont vous protéger. La bonne nouvelle, c'est que vous n'avez pas besoin d'un bureau de thérapeute pour commencer à y travailler. Voici cinq techniques d'ancrage que vous pouvez utiliser n'importe où, la prochaine fois que l'anxiété se manifeste.",
        "Commencez par vos sens. Nommez cinq choses que vous pouvez voir, quatre que vous pouvez toucher, trois que vous pouvez entendre, deux que vous pouvez sentir et une que vous pouvez goûter. Cet exercice simple, parfois appelé la technique du 5-4-3-2-1, ramène votre attention hors des pensées anxieuses et vers votre corps et votre environnement. Cela fonctionne parce que l'anxiété vit souvent dans le futur — dans ce qui pourrait arriver — alors que vos sens n'existent que dans le présent.",
        "Essayez la respiration carrée. Inspirez lentement en comptant jusqu'à quatre, retenez votre souffle quatre secondes, expirez pendant quatre secondes, puis retenez à nouveau avant de recommencer. Cela semble presque trop simple pour être efficace, mais ralentir votre respiration signale la sécurité à votre système nerveux, ce qui peut calmer un cœur qui s'emballe en une minute ou deux.",
        "Bougez votre corps, même brièvement. Une courte marche, étirer vos bras vers le haut, ou simplement décrisper votre mâchoire et vos épaules peut interrompre la tension physique que crée l'anxiété. Vous n'avez pas besoin d'un entraînement complet — même trente secondes de mouvement intentionnel peuvent changer la façon dont votre corps porte le stress.",
        "Nommez ce que vous ressentez, à voix haute si possible. Dire « je me sens anxieux/anxieuse en ce moment » peut sembler anodin, mais la recherche sur l'étiquetage des émotions montre que mettre un mot sur un sentiment peut en réduire l'intensité. Il ne s'agit pas de vous convaincre que l'anxiété n'existe pas — simplement de la reconnaître, ce qui lui enlève souvent une partie de son pouvoir.",
        "Ces techniques n'effaceront pas l'anxiété, et elles ne remplacent pas un accompagnement lorsque l'anxiété affecte votre quotidien, votre sommeil ou vos relations. Si l'anxiété vous suit depuis un moment, il pourrait être utile d'en parler à quelqu'un. Dans notre travail ensemble, nous bâtissons une boîte à outils qui vous est spécifiquement adaptée — pas une liste générique, mais des stratégies qui correspondent réellement à votre vie, à vos déclencheurs et à vos objectifs. Si vous souhaitez en parler, une consultation gratuite de 15 minutes est une façon simple et sans pression de commencer.",
      ],
    },
  },
  {
    slug: 'couple-therapy',
    coverImage: '/img/blog-couple.webp',
    category: 'Relationships',
    readMinutes: 4,
    en: {
      title: 'What Actually Happens in Couple Therapy',
      excerpt: "A look at what couple therapy really involves — and why it's not about deciding who's right.",
      body: [
        "Most couples wait an average of six years of being unhappy before seeking therapy — often until the problems feel too big to solve alone. If you're considering couple therapy but aren't sure what it actually involves, you're not alone in wondering. It's not about a therapist deciding who's right. It's about creating a space where both people can actually be heard.",
        "In our first session together, I'm not taking sides. My role is to slow down conversations that usually happen too fast — the ones that spiral into old arguments before either of you has said what you meant to say. We'll talk about what brought you in, what a good outcome would look like for each of you individually, and what patterns you've noticed repeating.",
        "A lot of couple therapy is about communication, but not in the way people expect. It's rarely about learning better words. It's about understanding what's underneath the words — the hurt, the fear of not mattering, the exhaustion of feeling unheard — and learning to express that directly instead of through frustration or withdrawal.",
        "We'll also look at the patterns that repeat: who pursues and who withdraws during conflict, what each of you needs to feel safe enough to be vulnerable, and where old wounds — sometimes from long before this relationship — are shaping how you react to each other now.",
        "Couple therapy isn't only for relationships in crisis. Some couples come in because they want to strengthen a good relationship, prepare for a major life change, or simply create better habits before small issues grow into bigger ones. There's no threshold of \"bad enough\" you need to reach first.",
        "What I can tell you is this: change is possible, even in relationships that feel stuck. It takes both people showing up honestly, and it takes time — but I've seen couples rebuild trust and communication they thought was gone for good. If you're ready to start, a free 15-minute consultation is a good first step, together or separately.",
      ],
    },
    fr: {
      title: 'Ce qui se passe réellement en thérapie de couple',
      excerpt: "Un aperçu de ce qu'implique réellement la thérapie de couple — et pourquoi il ne s'agit pas de déterminer qui a raison.",
      body: [
        "La plupart des couples attendent en moyenne six ans d'insatisfaction avant de consulter — souvent jusqu'à ce que les problèmes semblent trop importants pour être résolus seuls. Si vous envisagez la thérapie de couple sans trop savoir ce qu'elle implique réellement, vous n'êtes pas seul(e) à vous poser la question. Il ne s'agit pas d'un thérapeute qui décide qui a raison. Il s'agit de créer un espace où chacun peut réellement être entendu.",
        "Lors de notre première séance ensemble, je ne prends pas parti. Mon rôle est de ralentir des conversations qui, habituellement, vont trop vite — celles qui dérapent vers d'anciennes disputes avant que l'un de vous ait pu dire ce qu'il ou elle voulait vraiment dire. Nous parlerons de ce qui vous amène, de ce à quoi ressemblerait un bon résultat pour chacun de vous individuellement, et des schémas que vous avez remarqués se répéter.",
        "Une grande partie de la thérapie de couple porte sur la communication, mais pas de la façon dont on l'imagine habituellement. Il s'agit rarement d'apprendre de meilleurs mots. Il s'agit de comprendre ce qui se cache sous les mots — la blessure, la peur de ne pas compter, l'épuisement de se sentir incompris — et d'apprendre à exprimer cela directement plutôt qu'à travers la frustration ou le repli sur soi.",
        "Nous examinerons aussi les schémas qui se répètent : qui poursuit et qui se retire pendant un conflit, ce dont chacun de vous a besoin pour se sentir assez en sécurité pour être vulnérable, et où d'anciennes blessures — parfois bien antérieures à cette relation — influencent la façon dont vous réagissez l'un envers l'autre aujourd'hui.",
        "La thérapie de couple n'est pas réservée aux relations en crise. Certains couples viennent parce qu'ils souhaitent renforcer une relation qui va bien, se préparer à un grand changement de vie, ou simplement créer de meilleures habitudes avant que de petits enjeux ne deviennent plus grands. Il n'y a pas de seuil de « assez grave » à atteindre au préalable.",
        "Ce que je peux vous dire, c'est ceci : le changement est possible, même dans les relations qui semblent bloquées. Cela demande que les deux personnes se présentent avec honnêteté, et cela demande du temps — mais j'ai vu des couples reconstruire une confiance et une communication qu'ils croyaient perdues à jamais. Si vous êtes prêt(e)s à commencer, une consultation gratuite de 15 minutes est un bon premier pas, ensemble ou séparément.",
      ],
    },
  },
  {
    slug: 'navigating-grief',
    coverImage: '/img/blog-grief.webp',
    category: 'Grief',
    readMinutes: 4,
    en: {
      title: 'Navigating Grief With Patience, Not a Timeline',
      excerpt: "Grief doesn't follow a schedule. Here's what compassionate support through loss can actually look like.",
      body: [
        "Somewhere along the way, many of us absorbed the idea that grief should follow a schedule — that after a certain number of weeks or months, we should be \"back to normal.\" In practice, grief rarely works that way. It moves in waves, resurfaces at unexpected moments, and can look different from day to day, even hour to hour. If your grief hasn't followed a tidy timeline, there is nothing wrong with you.",
        "Grief isn't only about losing a person. It can follow the loss of a relationship, a role, a sense of who you used to be, or a future you had planned around someone or something. All of these losses deserve space, whether or not the people around you recognize them as \"grief-worthy.\"",
        "One of the hardest parts of grieving is the pressure — sometimes from others, often from ourselves — to grieve \"correctly.\" To feel sad but not too sad, for not too long. To keep functioning while also honouring what's been lost. In session, there's no correct way to grieve. Some days that looks like tears. Other days it looks like anger, numbness, or even relief, and all of those are allowed.",
        "Support through grief isn't about rushing you toward acceptance. It's about having a steady, non-judgmental presence while you make sense of a loss at whatever pace that takes — someone who won't flinch if you're still grieving a year later, and won't rush you if you're ready to talk about moving forward sooner than others expect.",
        "If your culture or faith shapes how you understand loss and mourning, that belongs in the room too. Grief support that ignores your spiritual or cultural framework isn't full support — it's support with pieces missing. In our work together, your beliefs and traditions around loss are part of the process, not something we work around.",
        "If you're grieving right now, please know that reaching out for support isn't a sign that you're grieving \"wrong.\" It's a sign that you're taking care of yourself through something genuinely hard. A free 15-minute consultation is a gentle way to see if this could be helpful.",
      ],
    },
    fr: {
      title: 'Traverser le deuil avec patience, pas avec un échéancier',
      excerpt: 'Le deuil ne suit pas d\'horaire. Voici à quoi peut ressembler un accompagnement bienveillant à travers la perte.',
      body: [
        "Quelque part en chemin, plusieurs d'entre nous avons intégré l'idée que le deuil devrait suivre un échéancier — qu'après un certain nombre de semaines ou de mois, nous devrions être « revenus à la normale ». Dans les faits, le deuil fonctionne rarement ainsi. Il avance par vagues, refait surface à des moments inattendus, et peut être différent d'un jour à l'autre, voire d'une heure à l'autre. Si votre deuil n'a pas suivi un échéancier bien rangé, il n'y a rien d'anormal chez vous.",
        "Le deuil ne concerne pas seulement la perte d'une personne. Il peut suivre la perte d'une relation, d'un rôle, d'une image de qui vous étiez, ou d'un avenir que vous aviez imaginé autour de quelqu'un ou de quelque chose. Toutes ces pertes méritent un espace, que les gens autour de vous les reconnaissent ou non comme un « vrai » deuil.",
        "L'une des parties les plus difficiles du deuil est la pression — parfois venant des autres, souvent de nous-mêmes — de vivre son deuil « correctement ». Être triste, mais pas trop, pas trop longtemps. Continuer à fonctionner tout en honorant ce qui a été perdu. En séance, il n'existe pas de bonne façon de vivre un deuil. Certains jours, cela ressemble à des larmes. D'autres jours, cela ressemble à de la colère, à un engourdissement, ou même à un soulagement — et tout cela est permis.",
        "Un accompagnement à travers le deuil ne consiste pas à vous précipiter vers l'acceptation. Il s'agit d'offrir une présence stable et sans jugement pendant que vous donnez un sens à une perte, au rythme que cela demande — quelqu'un qui ne sourcillera pas si vous êtes encore en deuil un an plus tard, et qui ne vous pressera pas si vous êtes prêt(e) à envisager d'aller de l'avant plus tôt que ce que les autres attendent.",
        "Si votre culture ou votre foi façonne votre façon de comprendre la perte et le deuil, cela a aussi sa place dans notre travail ensemble. Un accompagnement du deuil qui ignore votre cadre spirituel ou culturel n'est pas un accompagnement complet — il lui manque des morceaux. Dans notre travail ensemble, vos croyances et traditions entourant la perte font partie du processus, elles ne sont pas contournées.",
        "Si vous vivez un deuil en ce moment, sachez que demander du soutien n'est pas un signe que vous « faites mal » votre deuil. C'est un signe que vous prenez soin de vous à travers quelque chose de réellement difficile. Une consultation gratuite de 15 minutes est une façon douce de voir si cela pourrait vous aider.",
      ],
    },
  },
]
